{
 "title": "Video Filtering",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "250ms",
 "panels": [
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "alias": "All trafic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"BW\" WHERE (\"kind\" = 'total') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Robot Location",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"x\", \"y\" FROM \"entity_position\" ORDER BY time DESC LIMIT 10"
    },
    {
     "query": "SELECT \"x_a\", \"y_a\" FROM \"area_position\" ORDER BY time DESC LIMIT 5"
    },
    {
     "query": "SELECT \"x_b\", \"y_b\" FROM \"area_position\" ORDER BY time DESC LIMIT 5"
    },
    {
     "query": "SELECT \"x_c\", \"y_c\" FROM \"area_position\" ORDER BY time DESC LIMIT 5"
    },
    {
     "query": "SELECT \"x_d\", \"y_d\" FROM \"area_position\" ORDER BY time DESC LIMIT 5"
    }
   ]
  },
  {
   "title": "Per Stream Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Stream 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"BW\" WHERE (\"kind\" = 's1') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    },
    {
     "alias": "Stream 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"BW\" WHERE (\"kind\" = 's2') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    },
    {
     "alias": "Stream 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"BW\" WHERE (\"kind\" = 's3') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    },
    {
     "alias": "Stream 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"BW\" WHERE (\"kind\" = 's4') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    }
   ]
  },
  {
   "title": "Per Stream Unintended Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Stream 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"D\" WHERE (\"kind\" = 's1') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    },
    {
     "alias": "Stream 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"D\" WHERE (\"kind\" = 's2') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    },
    {
     "alias": "Stream 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"D\" WHERE (\"kind\" = 's3') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    },
    {
     "alias": "Stream 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BW",
     "query": "SELECT derivative(mean(\"value\"), 1s)/1000000*8 FROM \"D\" WHERE (\"kind\" = 's4') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "s1" }
     ]
    }
   ]
  }
 ]
}